// <auto-generated />
using CarDb.DAL.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CarDb.Migrations
{
    [DbContext(typeof(CarDbContext))]
    partial class CarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CarDb.Entities.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BrandName")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            BrandName = "Mercedes-Benz",
                            Country = "Germany"
                        },
                        new
                        {
                            BrandId = 2,
                            BrandName = "Volkswagen",
                            Country = "Germany"
                        },
                        new
                        {
                            BrandId = 3,
                            BrandName = "Renault",
                            Country = "France"
                        },
                        new
                        {
                            BrandId = 4,
                            BrandName = "Honda",
                            Country = "Japan"
                        });
                });

            modelBuilder.Entity("CarDb.Entities.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("ModelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.HasIndex("BrandId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            BrandId = 1,
                            ModelName = "Mercedes-Benz E220 CDI",
                            Price = 720000
                        },
                        new
                        {
                            CarId = 2,
                            BrandId = 2,
                            ModelName = "Volkswagen Jetta 1.6 TDI",
                            Price = 200000
                        },
                        new
                        {
                            CarId = 3,
                            BrandId = 3,
                            ModelName = "Renault Brodway",
                            Price = 50000
                        },
                        new
                        {
                            CarId = 4,
                            BrandId = 4,
                            ModelName = "Honda City",
                            Price = 95000
                        });
                });

            modelBuilder.Entity("CarDb.Entities.CarCustomer", b =>
                {
                    b.Property<int>("CarCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.HasKey("CarCustomerId");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.ToTable("CarCustomers");

                    b.HasData(
                        new
                        {
                            CarCustomerId = 1,
                            CarId = 1,
                            CustomerId = 1
                        },
                        new
                        {
                            CarCustomerId = 2,
                            CarId = 2,
                            CustomerId = 2
                        },
                        new
                        {
                            CarCustomerId = 3,
                            CarId = 3,
                            CustomerId = 3
                        },
                        new
                        {
                            CarCustomerId = 4,
                            CarId = 4,
                            CustomerId = 4
                        });
                });

            modelBuilder.Entity("CarDb.Entities.CarDetail", b =>
                {
                    b.Property<int>("CarDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<decimal>("EngineSize")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Fuel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Transmission")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarDetailId");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.ToTable("CarDetails");

                    b.HasData(
                        new
                        {
                            CarDetailId = 1,
                            CarId = 1,
                            EngineSize = 22m,
                            Fuel = "Diesel",
                            Transmission = "Automatic",
                            Year = 2014
                        },
                        new
                        {
                            CarDetailId = 2,
                            CarId = 2,
                            EngineSize = 16m,
                            Fuel = "Diesel",
                            Transmission = "Manual",
                            Year = 2013
                        },
                        new
                        {
                            CarDetailId = 3,
                            CarId = 3,
                            EngineSize = 16m,
                            Fuel = "Gasoline",
                            Transmission = "Manual",
                            Year = 1999
                        },
                        new
                        {
                            CarDetailId = 4,
                            CarId = 4,
                            EngineSize = 14m,
                            Fuel = "Gasoline",
                            Transmission = "Manual",
                            Year = 2007
                        });
                });

            modelBuilder.Entity("CarDb.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            FirstName = "Ali",
                            LastName = "ÇİÇEK"
                        },
                        new
                        {
                            CustomerId = 2,
                            FirstName = "Abudder",
                            LastName = "KANIK"
                        },
                        new
                        {
                            CustomerId = 3,
                            FirstName = "Şahin",
                            LastName = "BAYINDIR"
                        },
                        new
                        {
                            CustomerId = 4,
                            FirstName = "Muhittin",
                            LastName = "KARABOĞA"
                        });
                });

            modelBuilder.Entity("CarDb.Entities.Car", b =>
                {
                    b.HasOne("CarDb.Entities.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("CarDb.Entities.CarCustomer", b =>
                {
                    b.HasOne("CarDb.Entities.Car", "Car")
                        .WithMany("CarCustomers")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarDb.Entities.Customer", "Customer")
                        .WithMany("CarCustomers")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CarDb.Entities.CarDetail", b =>
                {
                    b.HasOne("CarDb.Entities.Car", "Car")
                        .WithOne("CarDetail")
                        .HasForeignKey("CarDb.Entities.CarDetail", "CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarDb.Entities.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarDb.Entities.Car", b =>
                {
                    b.Navigation("CarCustomers");

                    b.Navigation("CarDetail");
                });

            modelBuilder.Entity("CarDb.Entities.Customer", b =>
                {
                    b.Navigation("CarCustomers");
                });
#pragma warning restore 612, 618
        }
    }
}
